
disabled_rules:
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - cyclomatic_complexity

trailing_whitespace:
  ignores_empty_lines: true
  
identifier_name:
  excluded:
    - i
    - dl
    - id
    - ok
    - xp
